/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestSort */

#ifndef _Included_TestSort
#define _Included_TestSort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestSort
 * Method:    sortTest
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_TestSort_sortTest
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
